### ISSUE TITLE
SNSアイコンのリンクが死んでる

### ISSUE THREAD

**Issue by su8ru** [afes-website/front#278]
メニュー上の Instagram, 学園公式 へのリンクが死んでる

**Comment by su8ru** [comment]
[object タグをアンカーリンクで囲んでもリンクにならない \- Qiita](https://qiita.com/yo1000/items/53f31282b6b10e71b206)
のとおりに
```css
object {
  pointer-events: none;
}
```
ってしてみたら無事リンクが復活したんですが、tooltip も消えちゃいました（それはそう）

どうしよう………
